name: manage-azure-policy-cb1b97b1
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Configure_Azure_Defender_for_workload_protections_9ec83d1198784c7eaec33f18/**'
#      - .github/workflows/manage-azure-policy-cb1b97b1.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_cb1b97b1}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/Configure_Azure_Defender_for_workload_protections_9ec83d1198784c7eaec33f18/**
