name: manage-azure-policy-865ee780
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Configure_diagnostic_settings_for_Web_apps_to_Log_Analytics_workspace_(Premium_App_Service_plan)_62c160ed-02f6-4ab9-8607-32cc157cff6f/**'
#      - .github/workflows/manage-azure-policy-865ee780.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_865ee780}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Configure_diagnostic_settings_for_Web_apps_to_Log_Analytics_workspace_(Premium_App_Service_plan)_62c160ed-02f6-4ab9-8607-32cc157cff6f/**
